name: CI

on:
  pull_request:
    branches: ["*"] 
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }} with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies with pnpm
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Lint source code
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run tests coverage
        run: pnpm test:coverage
