name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Setup Node.js ${{ matrix.node-version }} with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lint source code
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Run tests coverage
        run: pnpm test:coverage
